services:
  mysql:
    image: mysql:8.0.37-bookworm # https://hub.docker.com/_/mysql
    container_name: mysql
    volumes:
      - type: tmpfs
        target: /var/log/mysql
        tmpfs:
          size: 100m
      - type: tmpfs
        target: /var/lib/mysql
        tmpfs:
          size: 500m
      - type: bind
        source: ./mysql
        target: /tmp/setup
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=inventory

  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION} # https://hub.docker.com/r/debezium/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION} # https://hub.docker.com/r/debezium/kafka
    container_name: kafka
    volumes:
      - type: tmpfs
        target: /kafka/logs
        tmpfs:
          size: 100m
      - type: tmpfs
        target: /kafka/data
        tmpfs:
          size: 100m
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  debezium:
    image: debezium/connect:${DEBEZIUM_VERSION} # https://hub.docker.com/r/debezium/connect
    container_name: debezium
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=__debezium_configs
      - OFFSET_STORAGE_TOPIC=__debezium_offsets
      - STATUS_STORAGE_TOPIC=__debezium_status
      # local docker
      # - BOOTSTRAP_SERVERS=kafka:9092
      # Confluent Cloud
      - BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - CONNECT_SASL_MECHANISM=PLAIN
      - CONNECT_SECURITY_PROTOCOL=SASL_SSL
      - CONNECT_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_API_KEY}" password="${KAFKA_API_SECRET}";
    depends_on:
      - mysql
      - kafka
    ports:
      - 8083:8083

  kafka-connect-ui:
    image: landoop/kafka-connect-ui:0.9.7 # https://hub.docker.com/r/landoop/kafka-connect-ui
    container_name: kafka-connect-ui
    environment:
      - CONNECT_URL=http://debezium:8083
    depends_on:
      - debezium
    ports:
      - 8080:8000
