services:
  mysql:
    image: mysql:8.0.37-bookworm # https://hub.docker.com/_/mysql
    volumes:
      - type: tmpfs
        target: /var/log/mysql
        tmpfs:
          size: 100m
      - type: tmpfs
        target: /var/lib/mysql
        tmpfs:
          size: 500m
      - type: bind
        source: ./mysql
        target: /tmp/setup
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=inventory
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
